version: 1.0.{build}

environment:
  # postgres
  PGUSER: postgres
  PGPASSWORD: Password12!
  PGDATABASE: nodedbconnect
  PG_PATH: C:\Program Files\PostgreSQL\9.5
  # mysql
  MYSQL_USER: root
  MYSQL_PWD: Password12!
  MYSQL_DB: nodedbconnect
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  # sql server
  SQLSERVER_HOST: localhost
  SQLSERVER_PORT: 1433
  SQLSERVER_USER: sa
  SQLSERVER_PASS: Password12!
  SQLSERVER_DB: nodedbconnect

services:
  - mysql57
  - postgresql95
  - mssql2008r2sp2

init:
  - npm -v
  - node -v
  - npm cache clean
  - SET PATH=%PG_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
  - ps: |
      Write-Host "Build worker environment variables:" -ForegroundColor Magenta
      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}

test: false

install:
  - npm install

build_script:

  # mysql
  - mysql -e "create database %MYSQL_DB%;" --user=root
  # postgres
  - createdb %PGDATABASE%
  # sqlserver
  - ps: ./appveyor-sqlserver.ps1 SQL2008R2SP2
  - sqlcmd -S %SQLSERVER_HOST%,%SQLSERVER_PORT% -U %SQLSERVER_USER% -P %SQLSERVER_PASS% -Q "CREATE DATABASE %SQLSERVER_DB%" -d "master"
  - npm run appveyor
