SELECT
	A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.NON_UNIQUE,
	A.INDEX_NAME, B.CONSTRAINT_TYPE,
	A.COLUMN_NAME, A.SEQ_IN_INDEX,
-- 	GROUP_CONCAT(A.COLUMN_NAME ORDER BY A.SEQ_IN_INDEX) AS COLUMN_LIST,
	A.COLLATION, A.CARDINALITY, A.SUB_PART, A.PACKED, A.NULLABLE,
	A.INDEX_TYPE, A.COMMENT
FROM
	INFORMATION_SCHEMA.STATISTICS A LEFT JOIN
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS B
ON
	A.TABLE_SCHEMA = B.TABLE_SCHEMA
	AND A.TABLE_NAME = B.TABLE_NAME
	AND A.INDEX_NAME = B.CONSTRAINT_NAME
-- GROUP BY
-- 	A.TABLE_NAME, A.INDEX_NAME;
ORDER BY
	A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.INDEX_NAME, A.SEQ_IN_INDEX;
